language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "nightly"

env:
    -
    - SPHINX=sphinx>1.7,<=1.8
    - SPHINX=sphinx>1.6,<=1.7
    - SPHINX=sphinx>1.5,<=1.6

install:
    - pip install --retries=20 .
    - pip install --retries=20 pycodestyle pyflakes
    - if [[ -n "$SPHINX" ]]; then pip install --retries=20 "$SPHINX"; fi

script:
    - if [[ -n "$SPHINX" ]]; then ./rstcheck.py -h | grep 'Sphinx is enabled'; fi
    - ./test_rstcheck.py
    - ./test.bash
    - pycodestyle ./*.py
    - pyflakes ./*.py
