sudo: false

language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
    - "pypy-5.4"
    - "pypy3"

env:
    -
    - LANG=
    - SPHINX=1

install:
    - python setup.py --quiet install
    - pip install pycodestyle pyflakes
    - if [[ "$SPHINX" == 1 ]]; then pip install sphinx; fi

script:
    - if [[ "$SPHINX" == 1 ]]; then ./rstcheck.py -h | grep 'Sphinx is enabled'; fi
    - ./test_rstcheck.py
    - ./test.bash
    - pycodestyle ./*.py
    - pyflakes ./*.py
